name: 'pleme-io · hardhat-deploy'
description: 'Deploy contracts via Hardhat.'
branding: { icon: 'upload', color: 'purple' }

inputs:
  network:
    required: true
  workdir:
    required: false
    default: "."

outputs:
  deployed-address:
    value: ${{ steps.run.outputs.deployed-address }}

runs:
  using: composite
  steps:
    - id: src
      shell: bash
      run: |
        {
          echo 'script<<TLISP_EOF'
          curl -sL https://raw.githubusercontent.com/pleme-io/actions/main/_tlisp-stdlib/stdlib.tlisp
          echo
          cat ${{ github.action_path }}/run.tlisp
          echo 'TLISP_EOF'
        } >> "$GITHUB_OUTPUT"
    - id: run
      uses: pleme-io/actions/tatara-script@v1
      with:
        script: ${{ steps.src.outputs.script }}
      env:
        NETWORK: ${{ inputs.network }}
        WORKDIR: ${{ inputs.workdir }}
