name: 'pleme-io · linkerd-inject'
description: 'Inject Linkerd sidecars into k8s manifests.'
branding: { icon: 'edit', color: 'blue' }

inputs:
  input:
    required: true
  output:
    required: false
    default: "injected.yaml"

outputs:
  injected:
    value: ${{ steps.run.outputs.injected }}

runs:
  using: composite
  steps:
    - id: src
      shell: bash
      run: |
        {
          echo 'script<<TLISP_EOF'
          curl -sL https://raw.githubusercontent.com/pleme-io/actions/main/_tlisp-stdlib/stdlib.tlisp
          echo
          cat ${{ github.action_path }}/run.tlisp
          echo 'TLISP_EOF'
        } >> "$GITHUB_OUTPUT"
    - id: run
      uses: pleme-io/actions/tatara-script@v1
      with:
        script: ${{ steps.src.outputs.script }}
      env:
        INPUT_ARG: ${{ inputs.input }}
        OUTPUT_ARG: ${{ inputs.output }}
