name: 'pleme-io · velero-backup'
description: 'Run velero backup create.'
branding: { icon: 'archive', color: 'green' }

inputs:
  backup-name:
    required: true
  namespaces:
    required: false
    default: ""

outputs:
  backup-name:
    value: ${{ steps.run.outputs.backup-name }}

runs:
  using: composite
  steps:
    - id: src
      shell: bash
      run: |
        {
          echo 'script<<TLISP_EOF'
          curl -sL https://raw.githubusercontent.com/pleme-io/actions/main/_tlisp-stdlib/stdlib.tlisp
          echo
          cat ${{ github.action_path }}/run.tlisp
          echo 'TLISP_EOF'
        } >> "$GITHUB_OUTPUT"
    - id: run
      uses: pleme-io/actions/tatara-script@v1
      with:
        script: ${{ steps.src.outputs.script }}
      env:
        BACKUP_NAME: ${{ inputs.backup-name }}
        NAMESPACES: ${{ inputs.namespaces }}
