name: 'pleme-io · istio-apply'
description: 'Apply Istio config (Gateway, VirtualService, etc).'
branding: { icon: 'upload', color: 'blue' }

inputs:
  manifests:
    required: true
  namespace:
    required: false
    default: "default"

outputs:
  applied:
    value: ${{ steps.run.outputs.applied }}

runs:
  using: composite
  steps:
    - id: src
      shell: bash
      run: |
        {
          echo 'script<<TLISP_EOF'
          curl -sL https://raw.githubusercontent.com/pleme-io/actions/main/_tlisp-stdlib/stdlib.tlisp
          echo
          cat ${{ github.action_path }}/run.tlisp
          echo 'TLISP_EOF'
        } >> "$GITHUB_OUTPUT"
    - id: run
      uses: pleme-io/actions/tatara-script@v1
      with:
        script: ${{ steps.src.outputs.script }}
      env:
        MANIFESTS: ${{ inputs.manifests }}
        NAMESPACE: ${{ inputs.namespace }}
