name: 'pleme-io · cdk-deploy'
description: 'Run cdk deploy for an AWS CDK app.'
branding: { icon: 'cloud', color: 'orange' }

inputs:
  stack:
    required: false
    default: "*"
  workdir:
    required: false
    default: "."

outputs:
  deployed:
    value: ${{ steps.run.outputs.deployed }}

runs:
  using: composite
  steps:
    - id: src
      shell: bash
      run: |
        {
          echo 'script<<TLISP_EOF'
          curl -sL https://raw.githubusercontent.com/pleme-io/actions/main/_tlisp-stdlib/stdlib.tlisp
          echo
          cat ${{ github.action_path }}/run.tlisp
          echo 'TLISP_EOF'
        } >> "$GITHUB_OUTPUT"
    - id: run
      uses: pleme-io/actions/tatara-script@v1
      with:
        script: ${{ steps.src.outputs.script }}
      env:
        STACK: ${{ inputs.stack }}
        WORKDIR: ${{ inputs.workdir }}
