name: 'pleme-io · goreleaser'
description: 'Run goreleaser to publish Go binaries to GH Releases.'
branding: { icon: 'upload', color: 'blue' }

inputs:
  config:
    required: false
    default: ".goreleaser.yml"

outputs:
  released:
    value: ${{ steps.run.outputs.released }}

runs:
  using: composite
  steps:
    - id: src
      shell: bash
      run: |
        {
          echo 'script<<TLISP_EOF'
          curl -sL https://raw.githubusercontent.com/pleme-io/actions/main/_tlisp-stdlib/stdlib.tlisp
          echo
          cat ${{ github.action_path }}/run.tlisp
          echo 'TLISP_EOF'
        } >> "$GITHUB_OUTPUT"
    - id: run
      uses: pleme-io/actions/tatara-script@v1
      with:
        script: ${{ steps.src.outputs.script }}
      env:
        CONFIG: ${{ inputs.config }}
